services:
  backend:
    build: ./backend
    container_name: dancelearn_backend
    command: python manage.py runserver 0.0.0.0:8000
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=True
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: dancelearn_frontend
    environment:
      - VITE_API_URL=http://localhost:8000/api
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend