# Generated by Django 4.2.11 on 2026-04-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cart_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creation_date', models.DateTimeField(blank=True, db_column='creation_date', null=True)),
            ],
            options={
                'db_table': 'cart_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_status', models.CharField(choices=[('active', 'activo'), ('completed', 'completado'), ('cancelled', 'cancelado')], default='active', max_length=20)),
                ('creation_date', models.DateTimeField(blank=True, db_column='creation_date', null=True)),
            ],
            options={
                'db_table': 'shopping_cart',
                'managed': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='itemcarrito',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='coreografia',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='ItemCarrito',
        ),
    ]
