# Generated by Django 4.2.11 on 2026-04-10 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('user', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='profesor_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('biography', models.CharField(blank=True, max_length=300, null=True)),
                ('years_of_experience', models.IntegerField()),
                ('billing_information', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'profesor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('email_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'user_email',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPhoneNumber',
            fields=[
                ('p_number_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_number', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'user_phone_number',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'managed': False},
        ),
    ]
