# Generated by Django 4.2.11 on 2026-03-21 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coreografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cancion', models.CharField(max_length=200)),
                ('artista', models.CharField(max_length=200)),
                ('genero', models.CharField(choices=[('salsa', 'Salsa'), ('bachata', 'Bachata'), ('merengue', 'Merengue'), ('pop', 'Pop'), ('hip_hop', 'Hip-Hop'), ('reggaeton', 'Reggaetón'), ('cumbia', 'Cumbia'), ('otro', 'Otro')], max_length=20)),
                ('nivel_dificultad', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen_portada', models.ImageField(upload_to='coreografias/')),
                ('numero_ventas', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('bailarin_invitado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coreografias_como_invitado', to=settings.AUTH_USER_MODEL)),
                ('profesor_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coreografias_como_principal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('url_video', models.URLField()),
                ('orden', models.PositiveIntegerField()),
                ('duracion', models.DurationField(blank=True, null=True)),
                ('coreografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='choreographies.coreografia')),
            ],
        ),
    ]
