# Generated by Django 4.2.11 on 2026-04-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_shoppingcart_and_more'),
        ('sales', '0002_bill_purchase_usercoreography_and_more'),
        ('choreographies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coreography',
            fields=[
                ('coreography_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=100)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('c_description', models.CharField(blank=True, max_length=500, null=True)),
                ('dificulty_level', models.CharField(choices=[('basic', 'basico'), ('intermediate', 'intermedio'), ('advanced', 'avanzado')], max_length=30)),
                ('song_name', models.CharField(blank=True, max_length=100, null=True)),
                ('song_genre', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('times_sold', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=20)),
                ('creation_date', models.DateTimeField(blank=True, db_column='creation_date', null=True)),
            ],
            options={
                'db_table': 'coreography',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_name', models.CharField(max_length=100)),
                ('video_url', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(blank=True, db_column='upload_date', null=True)),
            ],
            options={
                'db_table': 'video',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='videoclip',
            name='coreografia',
        ),
        migrations.DeleteModel(
            name='Coreografia',
        ),
        migrations.DeleteModel(
            name='VideoClip',
        ),
    ]
