# Generated by Django 4.2.11 on 2026-03-21 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('choreographies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], max_length=20)),
                ('numero_orden', models.CharField(max_length=50, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coreografia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='choreographies.coreografia')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='sales.venta')),
            ],
        ),
        migrations.CreateModel(
            name='DatosFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_factura', models.CharField(max_length=200)),
                ('email_factura', models.EmailField(max_length=254)),
                ('documento', models.CharField(max_length=20)),
                ('metodo_pago', models.CharField(choices=[('pse', 'PSE'), ('tarjeta', 'Tarjeta de crédito/débito')], max_length=20)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.venta')),
            ],
        ),
    ]
