# Generated by Django 4.2.11 on 2026-04-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('pse', 'pse'), ('card', 'card')], max_length=50)),
                ('creation_date', models.DateTimeField(blank=True, db_column='creation_date', null=True)),
                ('email_address', models.CharField(max_length=100)),
                ('titular_name', models.CharField(max_length=100)),
                ('document_number', models.CharField(max_length=50)),
                ('details', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'bill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateTimeField(blank=True, db_column='purchase_date', null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'purchase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserCoreography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'user_coreography',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='itemventa',
            name='coreografia',
        ),
        migrations.RemoveField(
            model_name='itemventa',
            name='venta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='DatosFacturacion',
        ),
        migrations.DeleteModel(
            name='ItemVenta',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
